### ISSUE TITLE
Review use of "mitigate" and "remediate" 

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#104]
Also noun forms (mitigation, remediation).

Review use to make sure they are consistent with and cite other standards throughout SSVC. 

This is a prerequisite for #74  #76 #77  and #78.

**Comment by laurie-tyz** [comment]
Completed review of the use of "mitigate", "remediation", "fix", and "patch".  After several rounds, Chuck was asked to do a complete review of the usage.

**Comment by cgyarbrough** [comment]
I have reviewed the usage of the relevant terms and have found them consistently used throughout and aligned with the proper DoDI (which was also properly referenced. No changes are needed.
