### ISSUE TITLE
Add Vul ID to SSVC vector format

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#108]
Breaking this out from #88 so it can be addressed independently

Consider including a slot for a vul ID. This needn't be CVE, could be VU#, JVN#, or just a locally-relevant case number from a ticketing system or scan finding ID. I'd probably put it closer to the front than back, so maybe SSVC/v2/VU#99999//

Adding a vul ID breaks some format symmetry with CVSS vectors but I don't think there's a requirement to maintain that degree of symmetry in the first place.

**Comment by sei-vsarvepalli** [comment]
> Breaking this out from #88 so it can be addressed independently
> 
> Consider including a slot for a vul ID. This needn't be CVE, could be VU#, JVN#, or just a locally-relevant case number from a ticketing system or scan finding ID. I'd probably put it closer to the front than back, so maybe SSVC/v2/VU#99999//
> 
> Adding a vul ID breaks some format symmetry with CVSS vectors but I don't think there's a requirement to maintain that degree of symmetry in the first place.

> Breaking this out from #88 so it can be addressed independently
> 
> Consider including a slot for a vul ID. This needn't be CVE, could be VU#, JVN#, or just a locally-relevant case number from a ticketing system or scan finding ID. I'd probably put it closer to the front than back, so maybe SSVC/v2/VU#99999//
> 
> Adding a vul ID breaks some format symmetry with CVSS vectors but I don't think there's a requirement to maintain that degree of symmetry in the first place.

May be not necessary? Today CVSS vector does not do this.  We can always provide a SSVC vector score along with a CVE or VU# id or in rare cases vendor ID INTEL-SA , Microsoft-Security-Advisory when it covers multiple CVEs

**Comment by ahouseholder** [comment]
If @j--- agrees, I'm ok with labeling this a wontfix and closing

**Comment by j---** [comment]
Can it be optional? 
I'm thinking the vector format is for a "not standing by itself" use case where it is a compressed version for charts, etc. I don't want to make it so long that it can't fulfill that function. I'm not sure totally when that happens.

**Comment by ahouseholder** [comment]
I think we are in a state where I think we are in agreement on "meh". Which, invoking YAGNI, means we shouldn't do this until there's a more compelling use case to justify it.

I'm closing this as wontfix for now. We can reopen or revisit in the future should the need arise.
