### ISSUE TITLE
Vector keys should allow more than 1 character

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#111]
Breaking this out of #106 for separate decidability

We should allow for vector keys and possibly value keys to be more than 1 character. We can declare by convention a preference for single character keys, but being able to accommodate longer ones without having to rev the spec will likely be convenient in the future. 

We are likely to run out of letters in the decision options first because we're already using a sizable fraction of 26 across all the trees. 

Within any given decision it's really only necessary that the option values are unique to that decision (i.e., "E:A" is not the same "A" as "D:A", but we can't have two "D:A"s). And it seems like if we have a single decision with >26 options maybe we're doing something wrong.

**Comment by ahouseholder** [comment]
I don't know if this is something that affects the json schema or if it is just something that goes into the text explaining the vector conventions.

**Comment by j---** [comment]
Need to add a line to vector key creation method to check for uniqueness and specify what to do if there is a collision.
