### ISSUE TITLE
Consider new stakeholder -- intermediate developer

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#12]
Some organizations are both developers and appliers. Most software developers use libraries, and so when a library has a vul, that change needs to be applied to the vulnerable product, and then the new version of the product needs to be distributed. SSVC v1 handles this as two separable decisions, one as an applier, the second as a developer. Is this the best way to handle this? How should SSVC facilitate communicating if a library is used by the vulnerable behavior / call is not exposed?

**Comment by ahouseholder** [comment]
This will touch on #5 too

**Comment by ahouseholder** [comment]
Are intermediate vendors really acting as appliers/remediators (using both old and potential new terms here)? Or are they simply doing the developer/supplier role but have a dependency on someone else before they can finish?

It seems to me that this is more of the latter. I think the developer/supplier tree is likely sufficient for that.

**Comment by zmanion** [comment]
I don't think we need an "intermediate vendor" tree. A supplier/developer/vendor may act a user/customer in a supply chain, but I think they still act as a "patch developer" or whatever the new term becomes. Their dependency on an upstream fix is important but not really part of SSVC, we intentionally do not consider "patch available."

**Comment by ahouseholder** [comment]
I'm closing this one as wontfix.
