### ISSUE TITLE
Consider the applicability of a transient score for downstream vendors as system owners

### ISSUE THREAD

**Issue by santosomar** [CERTCC/SSVC#144]
As a follow up to the conversation during the CERT/cc vendor meeting on May 3, 2021. I would like to humbly suggest the consideration of the potential use of a transient score. This is relevant when _the system owner_ is also downstream _vendor_. For example, Cisco using Red Hat Enterprise Linux in _product X_ and assigning a SSVC score to their "_product X_". Another example is a cloud provider as the _the system owner_, but of course, not the ultimate consumer (i.e., IaaS, PaaS).

**Comment by j---** [comment]
Thanks @santosomar . Can you help me understand your suggestion by explaining any similarities or differences to #12 ?

**Comment by santosomar** [comment]
Thank you! Sorry, I wasn't aware of #12. I just read it and saw the discussion and the decision. We can definitely close this issue. Sorry for the noise.

**Comment by santosomar** [comment]
Duplicate of #12

**Comment by j---** [comment]
No worries! We should periodically revisit this question to make sure our way of handling the situation still matches the community needs, so this is helpful. If the community needs change / need something different from SSVC and the decision in #12 in the future, we can re-open the issue with a clear statement of that to work on. For now, we'll leave it as is. Thanks!
