### ISSUE TITLE
Add vul chaining considerations to virulence

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#15]
Add vul chaining considerations to _automatability_, formerly known as _virulence_ [#9](https://github.com/CERTCC/SSVC/issues/9)

**Comment by ahouseholder** [comment]
What needs to change? Add some words about how automatability might be made easier in the presence of some other vul or context? Or that chains make it harder? Possibly just noting that vuls can be chained and that can change how you think about automation (in either direction)?

**Comment by j---** [comment]
Add something like this?
> Due to vulnerability chaining, there is some nuance as to whether reconnaissance can be automated. For example, consider a vulnerability A. If the systems vulnerable to A are usually not openly connected to incoming traffic (`[*Exposure*](#exposure)` is `[small](#exposure)` or `[controlled](#exposure)`), reconnaissance probably cannot be automated (as scans should be blocked, etc.). This fact would make ~virulence~ slow. However, if another vulnerability B with rapid ~virulence~ can be reliably used to chain to vulnerability A, then that automates reconnaissance of vulnerable systems. In such a situation, the analyst should continue to analyze vulnerability A to understand whether the remaining steps in the kill chain can be automated.

"slow" and "rapid" should be styled as `[slow](#automatability)` based on #40.
