### ISSUE TITLE
ssvc_v2.py out of date or data missing

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#155]
In https://github.com/CERTCC/SSVC/blob/main/src/ssvc_v2.py 

```
DATAPATH="../data/v2/csv"

PATHS = {
    'coord_pub': os.path.join(DATAPATH,"ssvc_2_coord-publish.csv"),
    'coord_triage': os.path.join(DATAPATH,"ssvc_2_coord-triage.csv"),
    'deployer': os.path.join(DATAPATH,"ssvc_2_deployer.csv"),
    'supplier': os.path.join(DATAPATH,"ssvc_2_supplier.csv"),
}
```

These files no longer exist. Did they get lost in a reorg of the files? Or should this script now be using JSON? If the latter, then do we have a script that converts CSVs/TSVs into proper JSON representations of trees?

**Comment by ahouseholder** [comment]
I think this was duped by #206, which was closed by #207
