### ISSUE TITLE
Update Trees at democert

### ISSUE THREAD

**Issue by tschmidtb51** [CERTCC/SSVC#160]
Please update the trees for developers and appliers at https://democert.org/ssvc to reflect the current state.

**Comment by sei-vsarvepalli** [comment]
Supplier tree has been added to the demo site.  The CSV files are also available for deployer, however the JSON format and the website content is pending at this time.   I will need a few more days to do a review of the various decision trees to consolidate some of the tree definitions and their relationships. 

Vijay

**Comment by j---** [comment]
Static latex deployer tree also needs to be updated to s/Mission and Well-being Impact/Human Impact/g as per the document. That's a todo for me.

**Comment by sei-vsarvepalli** [comment]
Hello @tschmidtb51 

The Deployer tree is also available at the demo site. Feedback welcome

https://democert.org/ssvc/

Thanks
Vijay

**Comment by sei-vsarvepalli** [comment]
closed by #174
