### ISSUE TITLE
Update JSON schemas to 2020-12

### ISSUE THREAD

**Issue by tschmidtb51** [CERTCC/SSVC#163]
Currently the schemas use Draft-4. This is outdated and makes it complex to use in in modern tools. Therefore, I suggest to update the schemas to Draft-2020-12. We have done the same for CSAF.

**Comment by sei-vsarvepalli** [comment]
Hello Thomas,

The schema should be updated now.

Vijay

**Comment by ahouseholder** [comment]
This appears to have been resolved by #165.
