### ISSUE TITLE
Structured way to represent all decision points in SSVC

### ISSUE THREAD

**Issue by sei-vsarvepalli** [CERTCC/SSVC#164]
There are a number of decision points which provide a Combined Value (for .e.g, Human Impact).  These are present in markdown files in a *decisions_points*.md in doc/md_src_files folder.  These decision points (called "complex" decisions in JSON schema) themselves are arrived at by combining other decision points for e.g., Human Impact combines Situated Safety and Mission Impact.  

For clarity and probably for smoother adoption, it will be good to represent these as "sub-trees" with their own CSV files that show the combined value and show these are calculated.  In the graphics, these decisions can be present also as a decision tree with its own value or outcome.

Vijay

**Comment by sei-vsarvepalli** [comment]
I believe we want to avoid this "sub-tree" idea - calling anything sub-tree. We are treating this "Complex Decision Points" as "Combined Value" in the future trees https://github.com/CERTCC/SSVC/discussions/289#discussioncomment-6877367 

> Based on recent conversations, I think we concluded that "compound decision points" like Human Impact and Utility only exist for notational convenience. That is, they were created in order to provide a visual compression of a tree representation so that it could fit into a single PDF page. In terms of data representation, they are entirely substitutable with their component atomic decision points' values.
> Because of this, we are leaning toward not versioning compound decision points, and instead recasting them as examples of how atomic decision points can be combined into new features for ease of communication when needed.

There is no need to represent these as sub-trees or as independent CSV files.

**Comment by ahouseholder** [comment]
Ok, closing this one as a `wontfix` then. I originally read this as the driver for the json schema, but that's because I only skimmed it quickly and focused mainly on the title. 

I'll drop a separate issue to make sure we pick up the need to modify the json schema to reflect #289 and #303.
