### ISSUE TITLE
How to use OSS criticality as information source?

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#166]
https://github.com/ossf/criticality_score

It seems like there may be use in using this as an input to Value Density. For example, if the score is at least X, then Value Density is Concentrated. Even if that is the right way to use it, setting the threshold will take some consideration.

**Comment by zmanion** [comment]
Possibly a separate issue: how criticality_score is determined.

https://github.com/ossf/criticality_score/blob/main/Quantifying_criticality_algorithm.pdf

Would SSVC-like techniques (decision trees) be an alternative (possibly better) way to determine criticality? The criticality score is measuring countable things (days, contributors, dependents, etc), which is different than CVSS, but there are weights. At least it's all transparent.

There is discussion about the definition and use of the word "criticality."

Would it make sense to add qualitative inputs, e.g., "this project does auth" or "expected to listen on internet?"

Where this discussion should end up: https://github.com/ossf/criticality_score/issues/

**Comment by j---** [comment]
This discussion is better handled under #168
