### ISSUE TITLE
Other related SSVC decisions

### ISSUE THREAD

**Issue by zmanion** [CERTCC/SSVC#168]
Capturing some other potential applications of SSVC, possibly already supported, possibly requiring different inputs and trees, but likely amenable to SSVC techniques.

How critical is this component? Is this component critical? Consider NIST EO-Critical, other definition(s) of critical.

Should I escalate this vulnerability beyond my standard response practice? (This *is* vulnerability response prioritization and is currently supported).

**Comment by zmanion** [comment]
LF OpenSSF critical projects work: https://github.com/ossf/wg-securing-critical-projects/

**Comment by zmanion** [comment]
https://fedoraproject.org/wiki/Critical_path_package

**Comment by j---** [comment]
Just as an update, I've been attending OSSF meetings (https://github.com/ossf/wg-securing-critical-projects) to try to follow up on this. 

My current thought is that once there are data sources for criticality, it should inform *Mission Impact* as a data source. In some cases, there may be structured data that enables support for assessments of *Public Safety Impact*, but mostly these efforts seem to be steering away from explicitly noting or exposing any safety related classifications. 

However, mostly these criticality things are talking about something different in the risk equation. The #35 issue is the aspect most closely related to this problem. High criticality justifies spending more on mitigation. #35 would see us talk about how much doing something would cost. Criticality should inform about how much is justified to spend. Neither are what SSVC v2 focuses on.

**Comment by j---** [comment]
Above comment is my answer to #166 as well.
