### ISSUE TITLE
ssvc-calc: Add coordinator and vendor trees

### ISSUE THREAD

**Issue by zmanion** [CERTCC/SSVC#169]
Low priority, add trees/selection options for
* Supplier 2.0
* Coordinator Triage 2.0
* Coordinator 2.0

**Comment by sei-vsarvepalli** [comment]
This is for the demo site? Supplier 2.0 already exists in the demo and also in Github https://github.com/CERTCC/SSVC/blob/main/ssvc-calc/Supplier-v2.0.0.json 

The following trees are pending for the demo site 
- Triage
- Deployer

**Comment by zmanion** [comment]
Sorry yes, the request is basically for the demo (and eventually "production") public calculator to support all of the trees: coordinator triage, coordinator publish, CISA coordinator, supplier, deployer.

**Comment by sei-vsarvepalli** [comment]
The Deployer tree has been added the demo site. Pending some validation it will get added in the next Pull Request. 

https://democert.org/ssvc/Deployer-v2.0.0.json

**Comment by sei-vsarvepalli** [comment]
More trees added to demo site as requested by @zmanion 

https://democert.org/ssvc/Coordinator-Triage-v2.0.0.json for Coordination centers like CERT/CC trying to decide whether to Triage a vulnerability report that has been submitted to them.

https://democert.org/ssvc/Coordinator-Publish-v2.0.0.json for Coordination centers like CERT/CC to pursue public notification or a public announcement of a vulnerability that is coordinated.

Note: These Coordination decisions may not be relevant to all types of CERT coordination centers.  Some CSIRT's may find this useful https://www.first.org/standards/frameworks/csirts/csirt_services_framework_v2.1

**Comment by sei-vsarvepalli** [comment]
Closed by #174
