### ISSUE TITLE
Exposure is fact of matter, not intent

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#17]
Exposure as written reads like the value is set to what the device should be (SMB or modbus may get set to small) instead of what the device is actually exposed as. "Unavoidable" probably is confusing here.

**Comment by ahouseholder** [comment]
My suggestion is to make two changes to the System Exposure section of 040_treesForVulMgmt.md:

- [ ] Add note to first paragraph of section indicating that "Exposure should be judged against the system in context as it is actually deployed, which may differ from how it is expected or common to be deployed. For example, the exposure of a CAN bus device will vary depending on whether a cellular modem is also present on the same bus.
- [ ] Modify _Unavoidable_ to a different word, perhaps _significant_ or _large_ or _unimpeded_ etc. (need to choose the right term)

**Comment by j---** [comment]
Agree with the first note. 

Agree that *Unavoidable* needs to change. What about "open"?
