### ISSUE TITLE
Abbreviated format of Coordinator-Triage-v2.0.0.json

### ISSUE THREAD

**Issue by fruehaufm** [CERTCC/SSVC#178]
Hi again,
I think I found another bug.
When using the `Coordinator-Triage-v2.0.0.json` in https://democert.org/ssvc/ the abbreviated format seems to generate some double entries. One example is `SSVCv2/P:N/C:N/R:N/A:O/E:A/A:N/V:D/A:N/V:D/A:N/V:D/A:N/V:D/U:L/U:M/R:D/2022-04-05T16:51:53Z/`.
I think there is some redundant information: `A:N/V:D/A:N/V:D/A:N/V:D/`.

Best regards
Michael

**Comment by fruehaufm** [comment]
The same issue seems to appear for `Deployer-v2.0.0.json`.
It's the case for Utility (as in `Coordinator-Triage-v2.0.0.json` as well) and there's something strange for Human Impact in my opinion: `SSVCv2/E:P/X:C/A:N/V:D/A:N/V:D/A:N/V:D/A:N/V:D/A:N/V:D/U:L/S:H/M:C/S:N/M:N/S:N/M:N/H:L/P:D/2022-04-05T17:23:28Z/`.
The redundant information is: `A:N/V:D/A:N/V:D/A:N/V:D/A:N/V:D/` and there seems to be something wrong with `S:N/M:F/S:N/M:N/S:N/M:N/` I think. I selected Situated Safety Impact as "Hazardous" and Mission Impact as "Crippled" for Human Impact. `S:H/M:C` makes sense to me. Do the other abbreviations have something to do with the dependencies to the "Safety Impact" values?

Best regards
Michael

**Comment by sei-vsarvepalli** [comment]
Hello @fruehaufm 

I think this is now fixed. It looks like there are residual/leftover Modals of the Complex Decision that gets the ssmc_vector creation confusing.  Can you check to make sure it is working alright?

Thanks
Vijay

**Comment by fruehaufm** [comment]
Hi @sei-vsarvepalli 
I think it only affected the Complex Decisions.
But now it looks good, thanks!
