### ISSUE TITLE
graphics links have inconsistent processing perspectives

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#181]
Currently, graphics links didn't work when displayed in a browser. It was linked as `![Suggested Supplier Tree](graphics/ssvc_2_supplier.pdf){ width=100% }` which didn't work from the perspective of the md file. The markdown file would need to have the link be to `![Suggested Supplier Tree](../graphics/ssvc_2_supplier.pdf){ width=100% }`.

However, the `doc/compile-citeproc.sh` script is run from the `doc` dir, so the links as `graphics/*pdf` are correct for that perspective. That's embedded in that script by the line `src="./md_src_files" `.

That is, from the perspective of the md file, the links don't work. But they work fine for the perspective of doc/compile-citeproc.sh. 

IIRC, originally I had the graphics folder inside md_src_files so that the compile script and the browser could reasonably run from the same directory location. There was separate feedback that no one could find the graphics when browsing the files with this set up, so they moved up a level in the hierarchy. However, this breaks this consistency between the script and the browser.

I would suggest the issue is to restore a consistent perspective for the compile script and the browser view.

I see two options. Return the `graphics` dir to `md_src_files` or move the `*.md` to `doc` rather than putting them in their own directory.
Are there any other options we can consider? 

Thanks to @fruehaufm for pointing this out in #175 .

**Comment by sei-vsarvepalli** [comment]
The embedding does not really work in a transparent way between GitHub website and a local git repository. I think it is not really worth fixing, as the use case for embedding is not really relevant to GitHub web UI itself.

I recommend we just note in the README file that the embedded will not display as they are intended for scripts. @fruehaufm - hopefully that is okay with you?

Thanks
Vijay

**Comment by fruehaufm** [comment]
@j--- 
The only other option, in my opinion, is to move `compile-citeproc.sh` to the `md_src_files` directory if there are no other dependencies.

Otherwise, a note in the README file as suggested by @sei-vsarvepalli would also work.

Best regards 
Michael

**Comment by j---** [comment]
symlink the graphics folder so it's in two places sounds like the best option, thanks, bit embarrassed I didn't think of that sooner.

**Comment by ahouseholder** [comment]
Given the change to the web site as the primary documentation target instead of PDF-building, I think this issue is now moot.
