### ISSUE TITLE
Automate PDF generation with github actions

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#184]
Once PR #180 is resolved, we should create a github action that can be triggered in a few different ways, including:

- [ ] on-demand on a particular branch
- [ ] automatically as part of the pulll request process

This will require (at least)

- [ ] installing requirements
- [ ] running the script
- [ ] commit and add the generated PDF

**Comment by j---** [comment]
#180 is resolved, and #194 set the versioning as semver. I don't see particular value in calver for us. The comments in the PDF generation script introduced in #194 suggest what I'm thinking, but we still need to make a number of decisions about how to actually functionally automate this. But I don't think there are any remaining blockers for this to go forward.

**Comment by j---** [comment]
I need to look a bit more, but I think we can use https://hub.docker.com/r/pandoc/latex to pull requirements.

**Comment by ahouseholder** [comment]
As of 8da5bcbfc7c33bf34767a6635baf9de2d604a487 the doc/compile-pdf.sh script throws an error because the image references are to `../graphics/foo.pdf` while it expects them to be in `./graphics/foo.pdf` (pandoc apparently uses relative paths from where it is run from). I was able to get it to work by `ln -s doc/graphics` (thus making `graphics` appear to be a peer to `doc`), but that's kludgy. I'm not sure if there is a good reason for the links in the `.md` files to be `../graphics...` instead of `./graphics` - it might be as simple as a search and replace fix.

**Comment by ahouseholder** [comment]
> As of [8da5bcb](https://github.com/CERTCC/SSVC/commit/8da5bcbfc7c33bf34767a6635baf9de2d604a487) the `doc/compile-pdf.sh` script throws an error because the image references are to `../graphics/foo.pdf` while it expects them to be in `./graphics/foo.pdf` (pandoc apparently uses relative paths from where it is run from). I was able to get it to work by `ln -s doc/graphics` (thus making `graphics` appear to be a peer to `doc`), but that's kludgy. I'm not sure if there is a good reason for the links in the `.md` files to be `../graphics...` instead of `./graphics` - it might be as simple as a search and replace fix.

Turns out that's covered by #181
