### ISSUE TITLE
Resolve discussion of risk owner workflow

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#215]
- [ ] Resolve discussion #214 into any relevant issues
- [ ] Create and link those issues

**Comment by ahouseholder** [comment]
It does not seem like the discussion this issue tracks is likely to resolve into implemented features before the 2.1 release, so my inclination is to remove this issue from the 2.1 project / milestone  while leaving the issue open so we can continue to track the discussion in #214 it into a future version.

**Comment by j---** [comment]
I think it's OK to move it out of 2.1.

**Comment by ahouseholder** [comment]
I think this was resolved by #308.
