### ISSUE TITLE
downsize options for applier tree

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#23]
225 is too many possible combinations for the Applier tree, have fewer. 
Directly a result of #21

**Comment by ahouseholder** [comment]
Just noting that #1 reduces the deployer (f.k.a. applier) tree. Not sure if that is sufficient. I suspect you had something more than that in mind.

**Comment by j---** [comment]
The main thing is that I want to add Utility explicitly to the deployer tree. (#19 ). So until that is also done, we shouldn't judge whether the tree is adequately downsized. But I think it will be.
