### ISSUE TITLE
Missing character warnings when compiling

### ISSUE THREAD

**Issue by jeroenh** [CERTCC/SSVC#234]
When I use `make` on a reasonably fresh OSX install, I get the following errors:

```
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
[WARNING] Missing character: There is no κ (U+03BA) (U+03BA) in font [lmroman10-regular]:mapping=t
```

**Comment by ahouseholder** [comment]
Just noting the missing character issue is also a problem with the github workflow [pandoc_html_pdf.yaml](../blob/main/.github/workflows/pandoc_html_pdf.yaml) that superseded the Makefile

See for example logs from https://github.com/CERTCC/SSVC/actions/runs/5271705795/jobs/9532963063

in lines [83-99](https://github.com/CERTCC/SSVC/blob/37944fcea11efcfc3379638b5508a4a488ec07f6/.github/workflows/pandoc_html_pdf.yaml#L83-L99) of that file.

**Comment by j---** [comment]
While it is more technically correct to use the greek kappa instead of a k, one solution would be to s/κ/k/g. We are not using super technically dense mathematical notation, so I don't think using k will cause any confusion?

**Comment by jeroenh** [comment]
To make it slightly clearer that you're using a variable, it might make sense to use *k* instead of a plain k.

**Comment by j---** [comment]
OK, so `s/κ/*k*/g`. But that works for me.
