### ISSUE TITLE
Replace Utility with Automatable in Deployer Tree

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#238]
See Discussion #221 for background discussion.

The change is to replace _Utility_ in the _Deployer Tree_ with _Automatable_.

This will require updates to at least:

- [x] src/enumerate-deployer-options.sh
- [x] ssvc-calc/Deployer-v2.0.0.json
- [x] data/csvs/deployer-options_v2.csv
- [x] doc/graphics/ssvc_2_deployer_SeEUMss.pdf
- [x] doc/graphics/ssvc_2_deployer_SeEUMss.tex

**Comment by ahouseholder** [comment]
feature/fix_238 has work in progress.

So far I've updated the generator script and the CSV file.

The new csv file is [/data/csvs/deployer-options_v2_1.csv](../blob/feature/fix_238/data/csvs/deployer-options_v2_1.csv)

In creating the new CSV, I used the following logic to choose the priority decision:

- If `v2.Utility == laborious` then `v2_1.Automatable = no` (36 leaf nodes)
- If `v2.Utility == super effective` then `v2_1.Automatable = yes` (36 leaf nodes)
- If `v2.Utility == efficient` then drop the row from the table (36 leaf nodes)

Note that this is consistent with the logic of _Utility_ in version 2.0. This method seemed to retain as much information as possible from the v2 tree (108 leaf nodes) into the smaller v2.1 tree (72 leaf nodes).

I have made no attempt to adjust any priorities from what they would have been in the v2 deployer tree.

Because the remaining changes to the `.json` and `.tex` files are derived from the `.csv`, we should to decide if the CSV is sufficient as-is before proceeding with further modifications. I'm comfortable with that, but comments are hereby encouraged.

**Comment by ahouseholder** [comment]
On second thought, the `.tex` (and subsequent `.pdf`) changes were easy enough, so they're in the [feature/fix_238](../tree/feature/fix_238) branch now too.

Once we decide to proceed, I'll most likely need to hand this issue off to @sei-vsarvepalli for the necessary `.json` changes.

**Comment by sei-vsarvepalli** [comment]
1. So the child_tree for `Human Impact` remains as-is, is that correct? 

https://github.com/CERTCC/SSVC/blob/feature/fix_238/data/csvs/child_trees/human-impact_v2.csv 

2. Does the `Utility` child tree still exists? or is it only to support deployer v2  situations ?

https://github.com/CERTCC/SSVC/blob/feature/fix_238/data/csvs/child_trees/utility_v2.csv

3. Deployer version currently is 2.0.0 using semantic like versioning. Should we bump that to 2.1.0 ?

**Comment by sei-vsarvepalli** [comment]
I have made the necessary changes and pushed it to the [feature/fix_238 branch](https://github.com/CERTCC/SSVC/tree/feature/fix_238) . The calculator with the new Deployer Tree versioned 2.1.0 is at https://certcc.github.io/SSVC/ssvc-calc/ ready for testing/review.  It has the 72 decisions and 103 nodes that seem to resemble what was generated as PDF.  

However..

I think there is still a bit of referencing of **Utility** and **Value Density** in various places that need to be reviewed and updated as it relates to Deployer tree. Like in `./doc/md_src_files/080_workedExample.md` and in `./doc/ssvc_v2-0.html`.  We should probably move all the older Deployer tree to an `archive` folder so it is not confusing. 

Vijay

**Comment by ahouseholder** [comment]
Noting necessity to change the logic example at the beginning of Prioritization since it specifically refers to the deployer tree.

**Comment by ahouseholder** [comment]
> I think there is still a bit of referencing of **Utility** and **Value Density** in various places that need to be reviewed and updated as it relates to Deployer tree. Like in `./doc/md_src_files/080_workedExample.md` and in `./doc/ssvc_v2-0.html`. 

Since the ssvc_v2-0.html file is generated from the markdown, we should focus on fixing the markdown and the html will eventually be taken care of when it's regenerated.

> We should probably move all the older Deployer tree to an `archive` folder so it is not confusing.

I deleted the `deployer-options_v2.csv` in this branch because we don't seem to have preserved previous versions as commits move on. The repository itself serves as a sufficient (IMO) archive of previous versions, so we can always go to the tagged 2.0 or 1.0 releases to retrieve the `.csv` or `.json` files from their respective versions. I don't think it's necessary to maintain an archive folder too, it just seems like extra version control and I'm ok with just letting git be git and leave the obsolete versions accessible via the commit history.

This does raise the side issue of whether we should be including version numbers in file names at all though -- because traceability of the git history could get wonky over time if every new version of a file has a different file name. I'll create a separate issue for that though.

**Comment by j---** [comment]
> I have made no attempt to adjust any priorities from what they would have been in the v2 deployer tree.

The logic here makes sense. If we want to review the recommended actions for the tree, that should be a separate issue, anyway. So I think this is a fine way to solve the issue at hand.
