### ISSUE TITLE
style guide inconsistency

### ISSUE THREAD

**Issue by jeroenh** [CERTCC/SSVC#251]
From [style-guide-how-to](https://github.com/CERTCC/SSVC/blob/main/doc/style-guide-how-to)
```
Names of decision points are capitalized and italics (md is * or _)
Values for specific decisions at a decision point are lower case and bold (md is ** or __)

```
[..]

```
So we would have:
[_Utility_](#utility) or [*Technical Impact*](#technical-impact) which might have values of [super effective](#utility) or [partial](#technical-impact)
```

The first statement about values seems inconsistent with the example, i.e. no styling is applied to the value "super effective" or "partial". Also note that in the PDF the links are not styled, and are not recognisable as links unless you hover over them.

I would suggest to change the PDF styling to make the links recognisable, and then changing the style guide to reflect that decision point values (in this document) should always reference the relevant section.

**Comment by ahouseholder** [comment]
I added everything except the `urlstyle` line in the fix_251 branch attached to this issue.

When I include that line I get:

```
Error producing PDF.
! Package keyval Error: urlstyle undefined.

See the keyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4018 \ProcessKeyvalOptions{Hyp}

make: *** [pdf] Error 43
```

I also can't see much difference in the resulting `/draft/ssvc.pdf` either.

**Comment by ahouseholder** [comment]
This PDF-doc related issue is superseded by the shift to https://certcc.github.io/SSVC as the main delivery channel for SSVC documentation.
