### ISSUE TITLE
Mention DoD's definition of Mission Essential Function as well

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#255]
@cgyarbrough wrote in a comment on #250, which modifies [`/doc/md_src_files/055_decision-points_2.md](../blob/main/doc/md_src_files/055_decision-points_2.md):
> ...have we considered the DOD's MEF definition and how it aligns with CISAs concept? I understand that the current context is CISA-based so this is appropriate. Just a question--not a show stopper.

_Originally posted by @cgyarbrough in https://github.com/CERTCC/SSVC/pull/250#pullrequestreview-1493732934_

**Comment by ahouseholder** [comment]
Copying my reply from [my comment](https://github.com/CERTCC/SSVC/pull/250#issuecomment-1610155127) on #250:

----

@cgyarbrough check my Google digging, but I found:

> **MEFs**. Select functions directly related to accomplishing the Department’s mission. Failure to
perform or sustain these functions, which directly support PMEF, would significantly affect the
Department of Defense’s ability to provide vital services or exercise authority, direction, and
control.

...which refers to

> **PMEFs**. The DoD MEFs, validated by the National Continuity Coordinator, which must be
performed in order to support the performance of the national essential functions before, during,
and in the aftermath of an emergency. PMEFs need to be performed continuously or resumed
within 12 hours after an event and maintained for up to 30 days or until normal operations can be
resumed.

...and

> **national essential functions**. The select functions that are necessary to lead and sustain the
United States during a catastrophic emergency and that, therefore, must be supported through
COOP, COG, and ECG capabilities.

In [DOD DIRECTIVE 3020.26 DOD CONTINUITY POLICY](https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodd/302026p.pdf)

Is that what you're referring to, or is there another definition elsewhere?

**Comment by ahouseholder** [comment]
Note this content is now found in [/doc/md_src_files/05_07_mission_impact.md](https://github.com/CERTCC/SSVC/blob/main/doc/md_src_files/05_07_mission_impact.md?plain=1)

**Comment by cgyarbrough** [comment]
Yes, that's what I had in mind when I brought up the question. DoD will want that included I am sure.
