### ISSUE TITLE
Update main readme to make current PDF easier to find

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#272]
https://github.com/CERTCC/SSVC/blob/0c5589f086feed20512cc0085694c6ad34b796c3/README.md?plain=1#L18C1-L20C64
and
https://github.com/CERTCC/SSVC/blob/0c5589f086feed20512cc0085694c6ad34b796c3/doc/README.md?plain=1#L6C1-L7C21
and 
https://github.com/CERTCC/SSVC/blob/0c5589f086feed20512cc0085694c6ad34b796c3/doc/README.md?plain=1#L13

Should be updated to explain those static PDFs are old and the current doc is now always available at:

https://github.com/CERTCC/SSVC/blob/main/doc/ssvc.pdf
and
https://github.com/CERTCC/SSVC/blob/main/doc/ssvc.html.

**Comment by ahouseholder** [comment]
It's a little more involved than that.

The doc/ssvc.pdf and doc/ssvc.html files are manually generated from the doc/Makefile. So they're recent but only if we've run "make all" in docs recently.

The literal _latest_ versions are in the output.zip of each build job at https://github.com/CERTCC/SSVC/actions/workflows/pandoc_html_pdf.yaml

At the time of this comment the actual latest is https://github.com/CERTCC/SSVC/suites/14140376400/artifacts/791907778

We can consider modifying the github action in the future to put the generated artifacts into the repository, but there will need to be some logic worked out such that the action itself isn't triggered by a push to `/doc` that it initiated itself.

**Comment by j---** [comment]
OK. We might settle for explaining that situation in the readme files and pointing out the "pdfs" folder is more historical now rather than current. And an explanation for how to get to the most recent auto-generated PDF.

It would be bad to send those workflows on an unending loop, I didn't anticipate that possibility. Thanks.

**Comment by jeroenh** [comment]
There is no specific reason the pdf and html are in that location though. They could be placed somewhere else to prevent the loop?
