### ISSUE TITLE
Update description of Human Impact

### ISSUE THREAD

**Issue by jeroenh** [CERTCC/SSVC#292]
Most new users of SSVC will now not know anything about the history of SSVC. So an introduction starting with "we changed this from a previous version" is not helpful to most readers. I can try to write up a new text for this and move the remark about changing from the pilot to a footnote?

**Comment by ahouseholder** [comment]
Recent discussions might be leading us towards framing the "compound decision points" like Human Impact and Utility as notational convenience to get the visual representation as a tree to fit onto one page, but not first-order objects in the way that the other decision points are.

In light of this, it's likely that how the Human Impact section shows up in the documentation will change significantly anyway, so it might make more sense to hold off on rewriting the intro to fit in better where it currently lives.

"compound decision point" = a decision point that is fully specified by a complete mapping of other decision points

**Comment by j---** [comment]
Agree with changing the intro. OK for it to be prioritized to be edited after the versioning documentation dust settles.
