### ISSUE TITLE
Move away from PDF as the main SSVC documentation vehicle

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#295]
The SSVC documentation has grown, and it's becoming unwieldy to try to fit everything into a single document that suits everyone's needs. Also, our experience with the CVD Guide and other such guidance shows that large PDFs tend to limit the audience to only the most dedicated readers.

This issue is to propose making a website based as the primary SSVC documentation vehicle going forward.
Note that Issue #294 is closely related and addresses the information architecture of such a site.

In terms of specific implementation suggestions:

1.  We can maintain a static site in this repository and set it up to auto-publish to certcc.github.io/SSVC
2. I have been exploring the following tech stack in my work on [Vultron](https://github.com/CERTCC/Vultron):
    - [mkdocs](https://www.mkdocs.org/) provides markdown-to-static-site capability
    - [material for mkdocs](https://squidfunk.github.io/mkdocs-material/) provides navigation, customization, look and feel, etc. to mkdocs sites
    - [mermaid](https://mermaid.js.org/) for diagrams
    - [pandoc](https://pandoc.org/) for LaTeX-to-markdown conversion (I don't think this applies to SSVC because the only raw `.tex` we have is for the tree diagrams, which pandoc is unlikely to be able to convert anyway

Plugins are available for file inclusion and other features that allow for a lot of customization.

Note that implementing this suggestion will likely break (at least initially) the `.md`-to-`.pdf` pipeline we currently have. We should consider whether being able to construct a single PDF remains a requirement if we have a documentation website. But one alternative could be "one big markdown file that includes all the others", which would effectively require us to maintain it like a manifest, but there could be automation potential there too. My suggestion would be that we do the web site version first, then figure out whether the single PDF doc is necessary afterwards.

**Comment by j---** [comment]
Narrowly RE latex, we only have latex src at this point to make images. Those images can be embedded in a website as they are. So I don't think the workflow needs to change for that. We stripped out all the latex being used to format math or anything during the conversion to markdown src. 
Pandoc uses latex and bibtex as an intermediary in order to make the citations from the markdown formatted nicely in the HTML/PDF currently. We probably want a citation management solution regardless of output format? Can mkdocs handle citation management?

**Comment by ahouseholder** [comment]
> Pandoc uses latex and bibtex as an intermediary in order to make the citations from the markdown formatted nicely in the HTML/PDF currently. We probably want a citation management solution regardless of output format? Can mkdocs handle citation management?

I think we have alternatives, in order by my preference at the moment (never having tried 1 or 3):

1. https://github.com/shyamd/mkdocs-bibtex
2. For Vultron my plan was to just replace refs with links directly to the relevant content. We could do that here too. 
3. https://tex.stackexchange.com/questions/610876/generating-markdown-from-bib-file has a few ideas about generating a references list from a .bib file. Not clear what to do with inline refs where they appear in docs.

**Comment by ahouseholder** [comment]
Option 1 seems to work in my local testing.
