### ISSUE TITLE
Reframe Decision Points as first-order objects in SSVC

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#296]
Building off of discussion #289, it seems like we are shifting towards making Decision Points be the first-order objects in SSVC.

We will need to update the documentation to reflect that, and there will be implications for the json schema definitions and code as well.

Roughly speaking, 
- Decision Points should be versioned objects following rules like those outlined in discussion #289.
- Decision functions (trees) are pinned to specific versions of specific Decision Points
- Outcomes (not the policy mapping, but the enumerated vocabulary) should probably be similarly versioned, I think. That might warrant a separate discussion.

We'll need to flesh out this issue with specifics, but for now I'm just capturing it to have something on record.

Also related: issue #252

**Comment by j---** [comment]
Is our first task to decide exactly the versioning rules we want to use?

**Comment by laurie-tyz** [comment]
[Decision Points.pptx](https://github.com/CERTCC/SSVC/files/12539638/Decision.Points.pptx)
This is my thinking of the decision points. 
Laurie

**Comment by ahouseholder** [comment]
> Decision Points should be versioned objects following rules like those outlined in discussion #289. 

- addressed by #350, which added [ADR-0002](https://github.com/CERTCC/SSVC/blob/main/docs/adr/0002-ssvc-decision-points-are-versioned.md)
- addressed by #368, which added [ADR-0006](https://github.com/CERTCC/SSVC/blob/main/docs/adr/0006-ssvc-decision-point-versioning-rules.md)

> Decision functions (trees) are pinned to specific versions of specific Decision Points

- addressed by #368, which added [ADR-0004](https://github.com/CERTCC/SSVC/blob/main/docs/adr/0004-ssvc-decision-point-groups-are-versioned.md) and [ADR-0005](https://github.com/CERTCC/SSVC/blob/main/docs/adr/0005-ssvc-decision-point-group-versioning.md)

> Outcomes (not the policy mapping, but the enumerated vocabulary) should probably be similarly versioned, I think. That might warrant a separate discussion.

Not yet addressed by a PR. 

## Remaining items for this issue:

- [ ] create an issue/PR if needed to address outcome set versioning
- [ ] identify where/how to update `docs/**/*.md` with words clarifying this "shift" in emphasis

**Comment by ahouseholder** [comment]
I think this issue is partially addressed in each of:

- #424 
- #447 

and that, taken in combination, this issue can be resolved once #447 is merged.
