### ISSUE TITLE
Update docs to reflect that decisions points and outcomes are ordered sets.

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#299]
In discussion #290, we concluded that Decision Points and Outcomes are ordered sets. We need to update the documentation to reflect that design choice.

Any update addressing this issue should include rationale in #290, summarized as follows:

- Rationale: requiring ordered sets allows us to apply consistency checks of the type "the priority of (a1,a2,a3) must be greater than or equal to the priority of (b1,b2,b3) if a1>b1, a2>b2, and a3>b3" where a1 and b1 are different values from decision point 1, a2 and b2 different values from decision point 2, and so on. That has turned out to be useful in evaluating the (literally) millions of possible CVSS v4 vectors, and seems like we'd be wise to consider instituting a similar approach.

-  when two values don't have a clear ordering relationship, they go in separate decision points (SSVC) / metrics (CVSS)

- The relevant dimension to which the ordering for both decision points and outcomes applies can be different for different decision points and outcomes. Sometimes this is a "better" or "worse" dimension, but it seems to generalize to a "more likely to act" or "less likely to act" sort of dimension.

**Comment by jeroenh** [comment]
Just to note, this assumption is already described in [doc/md_src_files/0704_tree_customization.md:61](https://github.com/CERTCC/SSVC/blob/5c4512d665b05d6e0f09eb802410ed90f9e1c05c/doc/md_src_files/07_04_tree_customization.md?plain=1#L61). But completely agree that this deserves to be described more extensively.

**Comment by ahouseholder** [comment]
We should also capture this in (probably two) ADRs:

- decision points are ordered sets
- outcomes are ordered sets

**Comment by ahouseholder** [comment]
I am currently of the opinion that

- #403 captures the ADR creation task

The rest is resolved by:

- #424
- #423
