### ISSUE TITLE
Use github wiki for meta-SSVC docs?

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#313]
We have two kinds of documentation in this repository:

1. SSVC - Documentation about the SSVC system
    - decision points
    - decision functions
    - gathering information
    - how to use SSVC
    - using the code
    - etc. 
2. Meta-SSVC - Documentation about how we manage the SSVC project
    - style guide
    - how we manage the project
    - etc.

Since we began turning (1) into a website, it's become more evident that (2) doesn't really fit there. My suggestion is that we move docs that fall into (2) into the Wiki that github provides for the project https://github.com/CERTCC/SSVC/wiki

Github wikis are basically parallel repositories for documentation only. So we would still have change tracking available, although we wouldn't necessarily need to enforce as much of a PR flow to meta-SSVC doc changes.

**Comment by j---** [comment]
Separating these two things makes sense. 
Does everything in the repo have to end up on the website version? As in, is there a lighter lift version where we just move everything about (2) to a folder and exempt that folder from being turned into website content?

**Comment by ahouseholder** [comment]
The website version only includes things in the `/docs` dir as configured in `mkdocs.yml`, plus anything that gets pulled in via an include statement in the markdown in `/docs`. I've already put the doc(s) I wanted to move into the [wiki](https://github.com/CERTCC/SSVC/wiki) and PR #320 does the cleanup.
