### ISSUE TITLE
Automate sync to staging repo

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#326]
Still thinking about this, but want to capture it for later.

Right now, updating the staging server means manually merging a new branch into the staging repo. It'd be nice to automate some of this. However I can see a few possible issues:

1. Sync on merge to `CERTCC/SSVC/main` would probably be fine, but it's kind of getting the horse and cart out of order.
2. We could set up a staging branch in `SSVC` that has an automatic job to push to `SSVC-staging`, but that doesn't seem to solve much because you still have to push to the staging branch so it's adding automation without reducing human steps.
3. Sync on a PR against `main` could be a problem because it allows anyone who can create a PR to influence content on the staging server.

That last one is probably the most problematic. I'm a bit stuck on what the right workflow would be. Any ideas?

**Comment by j---** [comment]
Is there a middle point where we first make a check list of all the human tasks, to make it easier for more people to be able to do the task? then cross train people so there aren't single points of failure. Then maybe the checklist will help us decide how to automate?

**Comment by ahouseholder** [comment]
We're working internally on prototyping these in some test repos to see which we prefer.

## Option 1: Action lives in the source (SSVC) repo, triggered by push to `main`

One option is to have an action runs in SSVC that triggers on push to SSVC:main, checks out SSVC-staging, merges main and pushes back to staging.

```mermaid
gitGraph
   commit
   branch staging
   checkout main
   commit
   checkout staging
   merge main
   checkout main
   commit
   checkout staging
   merge main
   checkout main
   commit
   checkout staging
   merge main
   checkout main
   commit
```

## Option 2: Action lives in the target (SSVC-staging) repo, triggered by a timer

The other option is polling-based, where the action runs on a timer in SSVC-staging and periodically polls for new updates from SSVC.

```mermaid
gitGraph
  commit
  commit
  branch staging
  checkout main
  commit
  commit
  commit
  commit
  checkout staging
  merge main
  checkout main
  commit
  commit
  commit
  checkout staging
  merge main
  checkout main
  commit
  commit
  commit
  commit
  commit
  checkout staging
  merge main
  checkout main
```

**Comment by laurie-tyz** [comment]
Preference for Option 1. 
* fewer steps
* Option 2 may result in an unintended update
* those approved to push to main should be few (adh, vijay, jono)

**Comment by j---** [comment]
Is there a code complexity difference for the two options? 
I'm basically trying to understand the draft ADR that would explain why we pick one over the other. 
Option 1 is more responsive and lets us fix typos and mistakes responsively. How much this response time matters depends on the polling interval. But we don't push that frequently, so maybe option 1 is more efficient. I assume it matters only a little if we have a poll in option 2 many times with no update.  And we already have reviews on pushes to main, so I am not too worried about people pushing to main out of turn in option 1 -- and if the poll time is frequent, there isn't much chance to undo any changes anyway. 

Since I can't detect a hugely important difference in the process outcomes (IIUC), then perhaps we go for whatever is easier to implement?

**Comment by ahouseholder** [comment]
I think this one is close to done, just waiting to confirm that https://github.com/CERTCC/SSVC-staging/actions/workflows/sync_upstream.yml successfully updates overnight.

It was easier to implement the scheduled-pull-from-staging version (option 2) than to do option 1, but we can revisit this as an improvement later if needed.

**Comment by ahouseholder** [comment]
Confirming that the scheduled update worked as intended and picked up all the recent PRs 

Log of success:
https://github.com/CERTCC/SSVC-staging/actions/runs/7792748135/job/21251318304 

This link will eventually age out of the logs, so excerpting the relevant evidence below.

```
Run git checkout main
  git checkout main
  git merge --no-edit upstream/main
  git push origin main
  shell: /usr/bin/bash -e {0}
Already on 'main'
Your branch is up to date with 'origin/main'.
Merge made by the 'ort' strategy.
 data/json/decision_points/human_impact_1_0_0.json  |   8 +-
 data/json/decision_points/human_impact 2_0_0.json  |  29 +++++
...
 40 files changed, 695 insertions(+), 241 deletions(-)
 create mode 100644 data/json/decision_points/human_impact_2_0_0.json
 create mode 100644 data/json/decision_points/mission_and_well-being_impact_1_0_0.json
...
To https://github.com/CERTCC/SSVC-staging
   922501d..7b8c710  main -> main
```
