### ISSUE TITLE
Add outcome set to reflect CISA outcomes

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#356]
Based on https://www.cisa.gov/sites/default/files/publications/cisa-ssvc-guide%20508c.pdf which describes the following outcome set:

| Value | Description |
|:---:|---|
|Track | The vulnerability does not require action at this time. The organization would continue to track the vulnerability and reassess it if new information becomes available. CISA recommends remediating Track vulnerabilities within standard update timelines.|
|Track*| The vulnerability contains specific characteristics that may require closer monitoring for changes. CISA recommends remediating Track* vulnerabilities within standard update timelines. |
| Attend | The vulnerability requires attention from the organization's internal, supervisory-level individuals. Necessary actions may include requesting assistance or information about the vulnerability and may involve publishing a notification, either internally and/or externally, about the vulnerability. CISA recommends remediating Attend vulnerabilities sooner than standard update timelines.|
| Act | The vulnerability requires attention from the organization's internal, supervisory-level and leadership-level individuals. Necessary actions include requesting assistance or information about the vulnerability, as well as publishing a notification either internally and/or externally. Typically, internal groups would meet to determine the overall response and then execute agreed upon actions. CISA recommends remediating Act vulnerabilities as soon as possible. |

We could incorporate these as part of the outcome set collection we're building. We might want to make the names a little less "stakeholder-specific", because I think they are a bit too jargony (looking at you, _track star_), but we could make them a bit more generic and just make them available for others to use.

I plan to cut a separate issue to address CISA's decision points.

**Comment by j---** [comment]
>
> , because I think they are a bit too jargony (looking at you, *track star*
> ),
>

I'd suggest "monitor" as a less jargon version of track star. It's already
in the text description.
