### ISSUE TITLE
Model theparanoids outcome set

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#358]
Based on https://github.com/theparanoids/PrioritizedRiskRemediation#risk-based-decision-tree-decisions

There they define a 6-level outcome set (I'm listing them in "least" to "most" order, which is the opposite of their number scale)

| Value | Description |
|:---:|---|
| 5 | Track |
| 4 | Track Closely |
| 3 | Attend |
| 2 | Attend |
| 1 | Act |
| 0 | Act ASAP |

I'm not suggesting that we directly adopt these values or names. It appears they adapted the names from the CISA ones (see #356). I'm not a fan of this name set, for what its worth.

However, I suppose it's more about providing a higher granularity 6-level outcome set. I've come across at least one other service management process that has six priority levels, so it seems like something we should be providing as one of our "standard bricks".

**Comment by sei-vsarvepalli** [comment]
@crashedmind makes reasonable trees, in fact even beautiful.

**Comment by ahouseholder** [comment]
Creating this issue also got me thinking about generalizing outcome sets by cardinality, see Discussion #359 to follow that thread.

**Comment by Crashedmind** [comment]
thanks for the kind words! 

For context, the changes I made are based on the fact that the high risk things are most important to me and likely others.
So....
1. I want more resolution at the high-risk end - so I split out the 4 Act nodes into 2. Lazily calling the top 2 "Act ASAP" vs the existing "Act". The other names came from CISA SSVC. The names are not so important for me.
2. The high risk things should be on top i.e. the CISA SSVC tree would be flipped vertically. I did not show that here in https://github.com/theparanoids/PrioritizedRiskRemediation#risk-based-decision-tree-decisions because I was showing something relative to the existing CISA SSVC tree
ref where I talk about this https://youtu.be/oMZN810xfck?t=1335

**Comment by ahouseholder** [comment]
> 2\. The high risk things should be on top i.e. the CISA SSVC tree would be flipped vertically. I did not show that here in https://github.com/theparanoids/PrioritizedRiskRemediation#risk-based-decision-tree-decisions because I was showing something relative to the existing CISA SSVC tree
>     ref where I talk about this https://youtu.be/oMZN810xfck?t=1335

In a UI representation of a full tree I probably agree with you. I'm thinking about the way it shows up in enumerations and such in the code, where low-to-high is significant to the way we're building graphs over the state combos etc.

**Comment by ahouseholder** [comment]
> I want more resolution at the high-risk end - so I split out the 4 Act nodes into 2. Lazily calling the top 2 "Act ASAP" vs the existing "Act". 

That's always been something I found odd about the CVSS score space, where they allocate 40% of the space to the things few people care about and 10% to the ones that make everyone jump. But it's one of those things that once the numbers are entrenched, they're hard to adapt.

**Comment by j---** [comment]
>     1. I want more resolution at the high-risk end - so I split out the 4 Act nodes into 2. Lazily calling the top 2 "Act ASAP" vs the existing "Act". The other names came from CISA SSVC. The names are not so important for me.

This seems like a good thing to support. 

- Track
- Monitor (per https://github.com/CERTCC/SSVC/issues/356#issuecomment-1782126332)

Do these things have time lines associated with them? for example
- Attend (gather more information within 7 business days)
- Attend (gather more information within 1 business day)
- Act (mitigation applied within 7 calendar days)
- Act (mitigation applied within 24 hours)

Would be different for different orgs, of course. 
Partly what i'm getting at with this, though, is that "act" and "attend' might be treated as distinct kinds of actions by a system deployer, which we didn't account for previously.
