### ISSUE TITLE
Update Coordination Decision on Staging Site

### ISSUE THREAD

**Issue by tqylorlewis** [CERTCC/SSVC#372]
In docs/howto/coordination_decisions.md, complete To Do tasks.

Under Coordinator Decision Points, include link to specific decision points.

Below Coordination Triage Decision Process, consider merge with docs/howto/coordinator_trees.md. 

Link: https://certcc.github.io/SSVC-staging/howto/coordination_decisions/#coordinator-decision-points

**Comment by ahouseholder** [comment]
This issue is blocked by #378 

My plan is to do a quick reorg PR to address #378 so we can unblock this.

**Comment by ahouseholder** [comment]
The decision points that need to be linked are:

- Report Public /reference/decision_points/report_public/
- Supplier Contacted /reference/decision_points/supplier_contacted/
- Report Credibility /reference/decision_points/report_credibility/
- Supplier Cardinality /reference/decision_points/supplier_cardinality/
- Supplier Engagement /reference/decision_points/supplier_engagement/
- Utility /reference/decision_points/utility/
- Public Safety Impact /reference/decision_points/public_safety_impact/

The above items need to be cleaned up and turned into relative links (e.g., `../../reference/decision_points/foo`)

**Comment by ahouseholder** [comment]
Blocked on changes pending in #405
