### ISSUE TITLE
Update Prepare on Staging Site

### ISSUE THREAD

**Issue by tqylorlewis** [CERTCC/SSVC#373]
In docs/howto/bootstrap/prepare.md, complete To Do task.

Under Define Inputs, consider rename.

Link: https://certcc.github.io/SSVC-staging/howto/bootstrap/prepare/#define-outcomes

**Comment by ahouseholder** [comment]
I don't think we're going to rename decision point sets right now, so we should just remove the TODO highlighted block from the page.

**Comment by ahouseholder** [comment]
Blocked on changes pending in #405

**Comment by laurie-tyz** [comment]
There are also a number of "!!! example" entries in that file.
