### ISSUE TITLE
Bootstrapping section should mention stakeholder roles involved in each phase

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#381]
This came out of a conversation that was generally around the question "Who needs to be involved in each step of the bootstrapping process?" and an idea that came up was that Decision Point concepts and values should generally be a boundary object understandable to both technical management and analysts, whereas datamapping is more about the analyst-level perspective that says how data will be used as evidence for assigning decision point values.

So the idea for this issue is to revise the bootstrapping docs to reflect those role distinctions.

**Comment by j---** [comment]
There is perhaps a middle layer of management between these operational roles and the risk owners. I don't know that needs to be specifically captured.  I don't have any other operational roles to add. 
Is PSIRT / CSIRT lead a different role? Those folks may have to explain their decisions to the public, and having decision points as boundary objects may help them do that.

**Comment by j---** [comment]
Thanks, this is good. some small suggestions.

> Risk owners should be involved in the development of the policy that affects said risk. Their involvement, no matter the degree, should be considered essential.

Maybe easier to just say "Risk owners *must* be involved in the development of the risk management policy represented by SSVC"

> ITSM (Information Technology Services Management)

Is there a link to a semi-standard definition of this term we could use?

**Comment by ahouseholder** [comment]
> > ITSM (Information Technology Services Management)
> 
> Is there a link to a semi-standard definition of this term we could use?

I came across it in the context of ITIL around 2007 or 2008. https://en.wikipedia.org/wiki/IT_service_management is what I usually point to, because it links back out to a bunch of related things (ITIL, TOGAF, COBIT, CMMI, etc.)

**Comment by j---** [comment]
Loose preference for wikipedia as a neutral source to reference. Otherwise, looks OK to me.
