### ISSUE TITLE
Clearly flag compound decision points as notionalal convenience in text

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#382]
> In text explanations, I agree that we should note that they're a bit different. And that we should allow for either explicit or implicit chaining of decision points (e.g., where policy A's outcome group is used as a decision point in policy B). This extends into the "outcomes are just a flavor of decision points" conversation I brought up elsewhere.

> But in terms of expressing the decision points themselves, I don't think they're materially different enough to change the way we collect them in the file system.

> My counterproposal then is that the text content on the individual pages for the compound decision points should make it clear that they're provided as a notational convenience and expected to be used with specific semantics (i.e., a hard-coded policy) when they do appear.

_Originally posted by @ahouseholder in https://github.com/CERTCC/SSVC/pull/370#discussion_r1388239355_

**Comment by ahouseholder** [comment]
Fixed by 

- #428
