### ISSUE TITLE
Consider reordering Understanding SSVC / SSVC How-To in site nav

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#489]
**Describe the solution you'd like**

The more I click around on the staging site, the more I notice how the _Understanding SSVC_ section has quite a bit more conceptual depth than the _SSVC How-To_ section. Which makes sense, as that's the purpose of these sections according to the [Diátaxis Framework](https://diataxis.fr/). However, when I initially created the nav, I went column-wise through

<img src="https://github.com/CERTCC/SSVC/assets/2594236/79e3014f-6653-476b-9e74-e8ef6f91d072" alt="drawing" width="300"/>

and now I think it might make more sense for the navigation to be row-wise.

In other words, the nav should be:

- Learning
- How-To
- Understanding
- Reference

which swaps _Understanding_ and _How-To_ from their current positions.

I think this represents a more reasonable content depth gradient that goes progressively deeper into the subject rather than going from shallow _Learning_ to sort-of-deep _Understanding_ back up to not-so-shallow _How-To_ before diving deep in _Reference_.

**Describe alternatives you've considered**

Leaving it as-is is the other option. My concern with this is that if you're just following the sequence links at the bottom of the pages, readers might feel like they have to get through a lot of the background (_Understanding_) material before they get to the thing they want, which is likely the _How-To_ content.

**Additional context**

In principle, this is a pretty simple change to reorder lines in `mkdocs.yml`. However, because it is also a significant divergence from the content ordering in the original PDFs, there might be some incidental copy edits necessary as a result.

**Comment by j---** [comment]
I agree with swapping these.
