### ISSUE TITLE
Define "risk"

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#49]
From @j--- in #43 :
> Do we have a definition of "risk" that we agree with?
> I'd like to avoid the simple (impact x likelihood) formulation of risk, not that it's wrong per se, but because it leaves out distribution of harms, correlated risks, and the uncertainty distribution on the likelihood.

**Comment by j---** [comment]
I suggest the ISO definition: 
> effect of uncertainty on objectives
> Note 1 to entry: An effect is a deviation from the expected — positive and/or negative.
> Note 2 to entry: Objectives can have different aspects (such as financial, health and safety, and environmental goals) and can apply at different levels (such as strategic, organization-wide, project, product and process).
> Note 3 to entry: Risk is often characterized by reference to potential events (3.5.1.3) and consequences (3.6.1.3), or a combination of these.
> Note 4 to entry: Risk is often expressed in terms of a combination of the consequences of an event (including changes in circumstances) and the associated likelihood (3.6.1.1) of occurrence.
> Note 5 to entry: Uncertainty is the state, even partial, of deficiency of information related to, understanding or knowledge of, an event, its consequence, or likelihood.

https://www.iso.org/obp/ui/#iso:std:iso:guide:73:ed-1:v1:en

**Comment by laurie-tyz** [comment]
Other definitions for Risk:  

DOD
Official definition of the United States Department of the term risk . risk Definition (US DoD) Official definition of the United States Department of the term risk . 1. Probability and severity of loss linked to hazards.
https://www.militaryfactory.com/dictionary/military-terms-defined.asp?term_id=4629#:~:text=Official%20definition%20of%20the%20United%20States%20Department%20of,Probability%20and%20severity%20of%20loss%20linked%20to%20hazards.

CSRC-NIST
risk. The level of impact on organizational operations (including mission, functions, image, or reputation), organizational assets, or individuals resulting from the operation of an information system given the potential impact of a threat and the likelihood of that threat occurring. [There are several more listed on https://csrc.nist.gov/glossary/term/risk .]

CISA
Definition of Risk
Alberts [Alberts 05] defines risk as “the possibility of suffering harm or loss.” Jones [Jones 05] defines risk as “the probable frequency and probable magnitude of future loss.” NIST’s Special Publication Risk Management Guide for Information Technology Systems states the following [Stoneburner 02]:
Risk is the net negative impact of the exercise of a vulnerability, considering both the probability and the impact of occurrence. Risk management is the process of identifying risk, assessing risk, and taking steps to reduce risk to an acceptable level.
Risk management is the process that allows IT managers to balance the operational and economic costs of protective measures and achieve gains in mission capability by protecting the IT systems and data that support their organizations’ missions. 
https://us-cert.cisa.gov/bsi/articles/best-practices/deployment-and-operations/risk-centered-practices
-----------
Where possible, we should ensure that none of them are in conflict with what is finally selected.

**Comment by j---** [comment]
I'm going to fight quite hard against the over-simplified "risk = likelihood x impact" definition, I'm afraid.  That's what I read all three of those to be.
