### ISSUE TITLE
Terminology Changes 

### ISSUE THREAD

**Issue by laurie-tyz** [CERTCC/SSVC#5]
"Work Item":
 - Review the various places the phrase is used
 - implement consistently
 - a work item may be something besides a 'patch'.  It could be a mitigation, accepting risk, or verifying product is at end of life.
 - [x] Update usage of "Work Item" to align with the above. 
 

For both of "Patch Applier" and "Patch Developer," the following considerations apply: 
 - actor description implies only binary actions. Implementing a mitigation, accepting risk or acknowledging product is EOL.
 - Suggest and discuss new ROLE identifiers.  Eg., system owner, consumer, defender, deployer, supplier, provider, or distributor.
 - Substitute the new ROLE identifier throughout the document.
 - Review the changes for awkward, or unclear language.
 - [x] change "Patch Applier" to "Supplier"
 - [x] change "Patch Developer" to "Deployer"

"Worst credible" 
- [x] substitute for "worst plausible"

"Out-of-Cycle"
- [x] substitute for "out-of-band" in document
- [x] substitute for "out-of-band" in trees and code that produces trees (@j--- )

**Comment by ahouseholder** [comment]
There's room for discussion, but I've been using "system owner" as the stand-in term for the individual or organization that controls the plugged-in boxes and has an interest/skin-in-the-game for the security of the deployed system. System owners might delegate some of those responsibilities to others (patch appliers, sysadmins, security guards, service providers, etc.) but the buck stops at the system owner I think.

**Comment by ahouseholder** [comment]
@laurie-tyz has the lead on this issue.

**Comment by laurie-tyz** [comment]
The term 'work item' is gone.  Replacement with the use of Work or Work unit. 

I will close out this item and begin working on Issue #46
