### ISSUE TITLE
SSVC Calc: Lowest zoom level zooms in to highest zoom level

### ISSUE THREAD

**Issue by cintek** [CERTCC/SSVC#508]
The more you move the zoom slider to the bottom the more the graph is zoomed out (like in the first screenshot). But if you move the slider completely to the bottom the graph is zoomed in at the highest zoom level (see second screenshot).

If I move the slider completely to the bottom I would expect that the graph would be very small (smaller than on the other zoom levels).

![1](https://github.com/CERTCC/SSVC/assets/100708552/9ae6794a-440c-4a8d-b076-c2a1b08495ad)
![2](https://github.com/CERTCC/SSVC/assets/100708552/cd0f11c2-b192-4c6d-9d29-2c476538528b)

**Comment by sei-vsarvepalli** [comment]
Hello @cintek 

Thanks for your feedback. We are actually moving the Dryad Calculator code for a more integrated SSVC site.  There is currently a staging site that is visible at https://sei-vsarvepalli.github.io/SSVC/ssvc-calc/

The Zoom Control is no longer enabled as it looks like its behavior is not consistent with various browsers. The native zoom controls on browsers seems to work okay enough to get the full view. So I have decided to abandon the zoom. The bug however is quite simple to fix if you plan to fork and maintain the code. 

https://github.com/CERTCC/SSVC/blob/5c4512d665b05d6e0f09eb802410ed90f9e1c05c/ssvc-calc/ssvc.js#L2350C1-L2361C2

The change is below.

```
function svgzoom(w) {
    var zf = w.value/w.max;
    /* Return on zero */
    if( zf <= 0) {
      console.log("The zoom focus too low!");
      return;
    }
    if(zf > 0.95) {
	var vbox = $('svg.mgraph').attr('viewBox');
	console.log("The viewbox should be left as-is "+vbox);
	return;
    }
    var fh = parseInt($('svg.mgraph').attr("height"));
    var fw = parseInt($('svg.mgraph').attr("width"));
    var vbox = "0 0 "+String(parseInt(fw/zf)) + " " + String(parseInt(fh/zf))
    $('svg.mgraph').attr('viewBox',vbox);
```

**Comment by ahouseholder** [comment]
Closing per @cintek's comment in https://github.com/CERTCC/SSVC/issues/510#issuecomment-1973410196
