### ISSUE TITLE
SSVC Calc: Use symbols for zoom slider

### ISSUE THREAD

**Issue by cintek** [CERTCC/SSVC#509]
To indicate what the zoom slider in the calculator is for it should use symbols like "+" and "-" so it's easier for users to see that the slider can be used for zooming in and out. This would increase the usability of the calculator.

**Comment by sei-vsarvepalli** [comment]
See comments in #508

**Comment by ahouseholder** [comment]
Closing per @cintek's comment in https://github.com/CERTCC/SSVC/issues/510#issuecomment-1973410196
