### ISSUE TITLE
SSVC Calc: Move buttons for mode and sample CVE to the top

### ISSUE THREAD

**Issue by cintek** [CERTCC/SSVC#510]
If you created a graph on smaller screens (and I don't mean smartphone screens although they are also affected) you may not see that there are buttons to choose a different mode or a sample CVE. Only if you look at the scrollbar you can see that there is more below the part you can see in the browser. So, if you didn't spot these buttons before you started to create a tree you may miss them completely.

The suggestion is to move the button for mode and sample to the top. Maybe next to "Show Full Tree" for a start.

**Comment by sei-vsarvepalli** [comment]
Hello @cintek 

Please check the up and coming version of our Calculator. It is slightly different and does not have the CVE import and has the Dropdown boxes up top. This may resolve your issue. The CVE import presumes values provided by CISA as examples and seemed less relevant for most use cases and is no longer in the new Calculator.

https://sei-vsarvepalli.github.io/SSVC/ssvc-calc/

**Comment by ahouseholder** [comment]
I closed #508 and #509 per https://github.com/CERTCC/SSVC/issues/510#issuecomment-1973410196
