### ISSUE TITLE
Switch JSON schemas to 2012 support for external merge support. 

### ISSUE THREAD

**Issue by sei-vsarvepalli** [CERTCC/SSVC#637]
**Is your feature request related to a problem? Please describe.**
As requested by our collaborators at OASIS working on CSAF https://github.com/oasis-tcs/csaf/issues/803 

 `Is it possible to update the JSON Schema that to Draft 2020-12?` from  @tschmidtb51 

I think very much so. But will verify with our staff and get this moving too.

**Comment by ahouseholder** [comment]
This issue is part of #640

**Comment by ahouseholder** [comment]
Resolved by #642
