### ISSUE TITLE
CSAF / SSVC integration

### ISSUE THREAD

**Issue by ahouseholder** [CERTCC/SSVC#640]
**Describe the solution you'd like**

This issue is for tracking integration with CSAF and SSVC

See also 

- OASIS CSAF issue: oasis-tcs/csaf#803
- https://groups.oasis-open.org/discussion/motion-for-803#bm87c96b9f-de9e-4b75-9a60-25f534cfbbda

**Comment by tschmidtb51** [comment]
@ahouseholder: Sorry for the late reply.
Unfortunately, #642 did not completely change the schema base. Here is the issues that I see so far:
- [ ] `definitions` is not longer valid. It needs to be changed to `$defs`
