### ISSUE TITLE
Looks like tab-based navigation has changed breaking some of the content navigation between JSON and text.

### ISSUE THREAD

**Issue by sei-vsarvepalli** [CERTCC/SSVC#644]
**Describe the bug**
Visit https://certcc.github.io/SSVC/reference/decision_points/supplier_engagement/ and see the tab-based navigation for `Text` and `JSON` fields. 

**To Reproduce**
Click on `Text` and `JSON` tabs under Supplier Engagement in this example

**Expected behavior**
Expect tab-based navigation to work. 

**Screenshots**
![Screenshot 2024-10-31 at 1 24 28 PM](https://github.com/user-attachments/assets/043026a7-626b-4b24-90a9-89c487cd7cfd)
vs 
![Screenshot 2024-10-31 at 1 24 19 PM](https://github.com/user-attachments/assets/ea5ccc6b-dca4-411f-9044-65813e39c65e)

**Platform details**

**Additional context**
I think the medics squidfunk libraries have changed quite a bit - this may have been broken for a few months from previous TypeScript library for squidfunk changes.

**Comment by ahouseholder** [comment]
Might be something that changed with 

- #638

Those pages use the include-markdown plugin

**Comment by ahouseholder** [comment]
> Indented code blocks must be surrounded by newlines
Now mkdocs-include-markdown-plugin will only detect indented code blocks if are surrounded by newlines, conforming to [CommonMark specification](https://spec.commonmark.org/0.28/#indented-code-blocks).

> In the practice this means that you must surround indented code blocks with newlines or possible link targets URLs will be rewritten to work in relative files.

**Comment by ahouseholder** [comment]
Resolved by #645
