### ISSUE TITLE
Include decision for what type of remediation to apply in the appropriate tree(s)

### ISSUE THREAD

**Issue by laurie-tyz** [CERTCC/SSVC#77]
The "fix" actions, once completed, should close the vulnerability management case and not invite recursion. This makes applying a patch qualitatively different from completing a remediation. It's unclear the best way to explain or notate this.

 - [ ] Include decision for what type of remediation to apply in the appropriate tree(s).

(Formerly part of issue #46 )

**Comment by j---** [comment]
My $0.02 is that we leave this as future work. We can mention it related to #38. I don't think we can complete this for v2.0.
